### ISSUE TITLE
File not found!

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [digitalprk/north_korean_embeddings#1]
Link below does not work!
https://drive.google.com/file/d/1LOa6nALYkhgCi_IUCFDHk2zvRjLAcWX2/view?usp=sharing

**Comment by digitalprk** [comment]
Sorry, fixed in [3331552](https://github.com/digitalprk/north_korean_embeddings/commit/3331552fc05f00a6c238c911e74a92ecf5c5b008)
